---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: apache-app
  name: apache-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: apache-app
    spec:
      containers:
      - image: bitnami/apache:2.4.23-r12
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 6
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 30
          timeoutSeconds: 5
        name: apache-app
        ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
        volumeMounts:
        - mountPath: /bitnami/apache
          name: apache-data
      volumes:
      - emptyDir: {}
        name: apache-data
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: apache-app
  name: apache-app
spec:
  ports:
  - name: http
    port: 80
    targetPort: http
  - name: https
    port: "443"
    targetPort: https
  selector:
    app: apache-app
  type: LoadBalancer